### ISSUE TITLE
No module name 'pysstv'

### ISSUE THREAD

**Issue by Warrior-4-Christ** [dnet/pySSTV#15]
I know this is probably just me being stupid, but what does this mean?

```
$ python3 pysstv
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pysstv/__main__.py", line 7, in <module>
    from pysstv import color, grayscale
ImportError: No module named 'pysstv'
```

**Comment by dnet** [comment]
You forgot the `-m` switch, try it like this:

    $ python3 -m pysstv

**Comment by Warrior-4-Christ** [comment]
> You forgot the `-m` switch...

Thanks.  It works perfectly now.
